# Generated by Django 2.2 on 2021-02-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210206_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_department',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
