# Generated by Django 2.2 on 2021-02-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
