# Generated by Django 2.2 on 2021-02-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('graduate', 'Graduate'), ('future student', 'Future Student')], max_length=10, null=True),
        ),
    ]
