# Generated by Django 2.2 on 2021-02-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210226_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('graduate', 'Graduate'), ('future student', 'Future Student')], max_length=100, null=True),
        ),
    ]
