# Generated by Django 2.2 on 2021-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210226_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_department',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
