# Generated by Django 2.2 on 2021-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_user_notif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif_User_Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='user_notif',
        ),
    ]
