# Generated by Django 2.2 on 2021-01-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210129_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notif_User_Emails',
        ),
    ]
