# Generated by Django 2.2 on 2021-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_delete_notif_user_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
