# Generated by Django 2.2 on 2021-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_notif_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif_user',
            name='user_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
