# Generated by Django 2.2 on 2021-01-30 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210130_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif_user',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
