# Generated by Django 2.2 on 2021-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_notif_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif_user',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
    ]
