# Generated by Django 2.2 on 2021-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20210130_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif_user',
            name='user_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
