# Generated by Django 2.2 on 2021-02-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_post_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
