# Generated by Django 2.2 on 2021-02-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_uploadfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
