# Generated by Django 2.2 on 2021-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20210203_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
