# Generated by Django 2.2 on 2021-02-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20210203_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='files',
            field=models.FileField(upload_to='post_images/'),
        ),
    ]
