# Generated by Django 2.2 on 2021-02-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20210203_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='files',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='forum.Post'),
        ),
    ]
