# Generated by Django 2.2 on 2021-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_auto_20210203_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
